// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: service/apaperFacadeService_10002.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Survey.Protocols {

  /// <summary>Holder for reflection information generated from service/apaperFacadeService_10002.proto</summary>
  public static partial class ApaperFacadeService10002Reflection {

    #region Descriptor
    /// <summary>File descriptor for service/apaperFacadeService_10002.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ApaperFacadeService10002Reflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CidzZXJ2aWNlL2FwYXBlckZhY2FkZVNlcnZpY2VfMTAwMDIucHJvdG8SBmRv",
            "dGJwZRoTZG90YnBlX29wdGlvbi5wcm90bxoUbWVzc2FnZS9hcGFwZXIucHJv",
            "dG8ylQEKE0FQYXBlckZhY2FkZVNlcnZpY2USdwoMR2V0QVBhcGVyU3RhEhcu",
            "ZG90YnBlLkdldFFQYXBlclN0YVJlcRoULmRvdGJwZS5RUGFwZXJTdGFSc3Ai",
            "ONDzGAHa8xgwCg8vYXBpL3FwYXBlci9zdGESA2dldBoY6I635Y+W6Zeu5Y23",
            "57uf6K6h5L+h5oGvGgXI8xiSTkIZSAGqAhBTdXJ2ZXkuUHJvdG9jb2xz6PMY",
            "AVAAYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::DotBPE.Protobuf.DotbpeOptionReflection.Descriptor, global::Survey.Protocols.ApaperReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
