// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: service/apaperService_20002.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Survey.Protocols {

  /// <summary>Holder for reflection information generated from service/apaperService_20002.proto</summary>
  public static partial class ApaperService20002Reflection {

    #region Descriptor
    /// <summary>File descriptor for service/apaperService_20002.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ApaperService20002Reflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiFzZXJ2aWNlL2FwYXBlclNlcnZpY2VfMjAwMDIucHJvdG8SBmRvdGJwZRoT",
            "ZG90YnBlX29wdGlvbi5wcm90bxoUbWVzc2FnZS9hcGFwZXIucHJvdG8yvAMK",
            "DUFQYXBlclNlcnZpY2UScAoKU2F2ZUFQYXBlchIVLmRvdGJwZS5TYXZlQVBh",
            "cGVyUmVxGhUuZG90YnBlLlNhdmVBUGFwZXJSc3AiNNDzGAHa8xgsChAvYXBp",
            "L2FwYXBlci9zYXZlEgRwb3N0GhLkv53lrZjnrZTljbfkv6Hmga8SdgoPUXVl",
            "cnlBUGFwZXJMaXN0EhYuZG90YnBlLlF1ZXJ5QVBhcGVyUmVxGhUuZG90YnBl",
            "LkFQYXBlckxpc3RSc3AiNNDzGALa8xgsChEvYXBpL2FwYXBlci9xdWVyeRID",
            "YWxsGhLmn6Xor6LnrZTljbfkv6Hmga8SaAoJR2V0QVBhcGVyEhQuZG90YnBl",
            "LkdldEFQYXBlclJlcRoRLmRvdGJwZS5BUGFwZXJSc3AiMtDzGAPa8xgqCg8v",
            "YXBpL2FwYXBlci9nZXQSA2dldBoS6I635Y+W562U5Y235L+h5oGvEk8KDEdl",
            "dEFQYXBlclN0YRIdLmRvdGJwZS5HZXRBUGFwZXJTdGFEZXRhaWxSZXEaGi5k",
            "b3RicGUuQVBhcGVyU3RhRGV0YWlsUnNwIgTQ8xgEGgbI8xiinAFCGUgBqgIQ",
            "U3VydmV5LlByb3RvY29sc+jzGAFQAGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Tomato.Protobuf.TomatoOptionReflection.Descriptor, global::Survey.Protocols.ApaperReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
