// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: service/qpaperService_20001.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Survey.Protocols {

  /// <summary>Holder for reflection information generated from service/qpaperService_20001.proto</summary>
  public static partial class QpaperService20001Reflection {

    #region Descriptor
    /// <summary>File descriptor for service/qpaperService_20001.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static QpaperService20001Reflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiFzZXJ2aWNlL3FwYXBlclNlcnZpY2VfMjAwMDEucHJvdG8SBmRvdGJwZRoT",
            "ZG90YnBlX29wdGlvbi5wcm90bxoUbWVzc2FnZS9xcGFwZXIucHJvdG8ynwQK",
            "DVFQYXBlclNlcnZpY2UScAoKU2F2ZVFQYXBlchIVLmRvdGJwZS5TYXZlUVBh",
            "cGVyUmVxGhUuZG90YnBlLlNhdmVRUGFwZXJSc3AiNNDzGAHa8xgsChAvYXBp",
            "L3FwYXBlci9zYXZlEgRwb3N0GhLkv53lrZjpl67ljbfkv6Hmga8ScAoPUXVl",
            "cnlRUGFwZXJMaXN0EhYuZG90YnBlLlF1ZXJ5UVBhcGVyUmVxGhUuZG90YnBl",
            "LlFQYXBlckxpc3RSc3AiLtDzGALa8xgmChEvYXBpL3FwYXBlci9xdWVyeRID",
            "YWxsGgzmn6Xor6LliJfooagSawoJR2V0UVBhcGVyEhQuZG90YnBlLkdldFFQ",
            "YXBlclJlcRoRLmRvdGJwZS5RUGFwZXJSc3AiNdDzGAPa8xgtChIvYXBpL3Fw",
            "YXBlci9zaW1wbGUSA2dldBoS6I635Y+W6Zeu5Y235L+h5oGvEnYKDUdldFFQ",
            "YXBlckZ1bGwSFC5kb3RicGUuR2V0UVBhcGVyUmVxGhUuZG90YnBlLlFQYXBl",
            "ckZ1bGxSc3AiONDzGATa8xgwCg8vYXBpL3FwYXBlci9nZXQSA2dldBoY6I63",
            "5Y+W6Zeu5Y236K+m5oOF5L+h5oGvEj0KDkFkZEFQYXBlckNvdW50EhQuZG90",
            "YnBlLkFkZEFQYXBlclJlcRoPLmRvdGJwZS5Wb2lkUnNwIgTQ8xgFGgbI8xih",
            "nAFCGUgBqgIQU3VydmV5LlByb3RvY29sc+jzGAFQAGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::DotBPE.Protobuf.DotbpeOptionReflection.Descriptor, global::Survey.Protocols.QpaperReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
