// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: service/userService_20003.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Survey.Protocols {

  /// <summary>Holder for reflection information generated from service/userService_20003.proto</summary>
  public static partial class UserService20003Reflection {

    #region Descriptor
    /// <summary>File descriptor for service/userService_20003.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UserService20003Reflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch9zZXJ2aWNlL3VzZXJTZXJ2aWNlXzIwMDAzLnByb3RvEgZkb3RicGUaE2Rv",
            "dGJwZV9vcHRpb24ucHJvdG8aEm1lc3NhZ2UvdXNlci5wcm90bzKcBAoLVXNl",
            "clNlcnZpY2USZgoIUmVnaXN0ZXISEy5kb3RicGUuUmVnaXN0ZXJSZXEaEy5k",
            "b3RicGUuUmVnaXN0ZXJSc3AiMNDzGAHa8xgoChIvYXBpL3VzZXIvcmVnaXN0",
            "ZXISBHBvc3QaDOazqOWGjOeUqOaItxKJAQoFTG9naW4SEC5kb3RicGUuTG9n",
            "aW5SZXEaEC5kb3RicGUuTG9naW5Sc3AiXNDzGALa8xhUCg8vYXBpL2dhdGUv",
            "bG9naW4SBHBvc3QaDOeUqOaIt+eZu+W9lSotU3VydmV5R2F0ZXdheS5Mb2dp",
            "blBvc3RQcm9jZXNzcyxTdXJ2ZXlHYXRld2F5Em0KBEVkaXQSEy5kb3RicGUu",
            "RWRpdFVzZXJSZXEaEy5kb3RicGUuRWRpdFVzZXJSc3AiO9DzGAPa8xgzCg4v",
            "YXBpL3VzZXIvc2F2ZRIEcG9zdBob5L+d5a2Y5L+u5pS555qE55So5oi35L+h",
            "5oGvEjsKC0dldFVzZXJJbmZvEhIuZG90YnBlLkdldFVzZXJSZXEaEi5kb3Ri",
            "cGUuR2V0VXNlclJzcCIE0PMYBBJlCgpDaGVja0xvZ2luEg8uZG90YnBlLlZv",
            "aWRSZXEaEi5kb3RicGUuR2V0VXNlclJzcCIy0PMYBdrzGCoKDy9hcGkvZ2F0",
            "ZS9jaGVjaxIDZ2V0GhLojrflj5bnlKjmiLfkv6Hmga8aBsjzGKOcAUIZSAGq",
            "AhBTdXJ2ZXkuUHJvdG9jb2xz6PMYAVAAYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::DotBPE.Protobuf.DotbpeOptionReflection.Descriptor, global::Survey.Protocols.UserReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
