// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: S100_MathService.proto
#region Designer generated code

using System.Threading.Tasks;
using Tomato.Rpc;

namespace Math.ServiceDefinition 
{
    /// <summary>   
    /// 数学服务 , 
    /// </summary>
    [RpcService(100)]
    public interface IMathService
    {

        /// <summary>
        /// 加法方法，不用添加Async后缀       
        /// </summary>    
        [RpcMethod(1)]
        Task<RpcResult<SumRes>> SumAsync(SumReq req);

    }
}
#endregion